# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\NMSU_Software_Projects\SWTDI_GUI\SWTDI_V0_0_4\mainWindowV6.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_InOutlet_1_Window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1719, 1085)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tab_1 = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_1.setGeometry(QtCore.QRect(0, 0, 1591, 871))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tab_1.setFont(font)
        self.tab_1.setObjectName("tab_1")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 160, 141, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labels_layout = QtWidgets.QVBoxLayout()
        self.labels_layout.setObjectName("labels_layout")
        self.voltage_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.voltage_label.setFont(font)
        self.voltage_label.setObjectName("voltage_label")
        self.labels_layout.addWidget(self.voltage_label)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.labels_layout.addWidget(self.line)
        self.current_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.current_label.setFont(font)
        self.current_label.setObjectName("current_label")
        self.labels_layout.addWidget(self.current_label)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.labels_layout.addWidget(self.line_3)
        self.power_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.power_label.setFont(font)
        self.power_label.setObjectName("power_label")
        self.labels_layout.addWidget(self.power_label)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.labels_layout.addWidget(self.line_5)
        self.reactive_power_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.reactive_power_label.setFont(font)
        self.reactive_power_label.setObjectName("reactive_power_label")
        self.labels_layout.addWidget(self.reactive_power_label)
        self.line_7 = QtWidgets.QFrame(self.layoutWidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.labels_layout.addWidget(self.line_7)
        self.temperature_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.temperature_label.setFont(font)
        self.temperature_label.setObjectName("temperature_label")
        self.labels_layout.addWidget(self.temperature_label)
        self.horizontalLayout.addLayout(self.labels_layout)
        self.dyn_labels_layout = QtWidgets.QVBoxLayout()
        self.dyn_labels_layout.setObjectName("dyn_labels_layout")
        self.voltage_dyn_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.voltage_dyn_label.setFont(font)
        self.voltage_dyn_label.setObjectName("voltage_dyn_label")
        self.dyn_labels_layout.addWidget(self.voltage_dyn_label)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.dyn_labels_layout.addWidget(self.line_2)
        self.current_dyn_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.current_dyn_label.setFont(font)
        self.current_dyn_label.setObjectName("current_dyn_label")
        self.dyn_labels_layout.addWidget(self.current_dyn_label)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.dyn_labels_layout.addWidget(self.line_4)
        self.power_dyn_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.power_dyn_label.setFont(font)
        self.power_dyn_label.setObjectName("power_dyn_label")
        self.dyn_labels_layout.addWidget(self.power_dyn_label)
        self.line_6 = QtWidgets.QFrame(self.layoutWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.dyn_labels_layout.addWidget(self.line_6)
        self.reactive_power_dyn_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.reactive_power_dyn_label.setFont(font)
        self.reactive_power_dyn_label.setObjectName("reactive_power_dyn_label")
        self.dyn_labels_layout.addWidget(self.reactive_power_dyn_label)
        self.line_8 = QtWidgets.QFrame(self.layoutWidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.dyn_labels_layout.addWidget(self.line_8)
        self.temperature_dyn_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.temperature_dyn_label.setFont(font)
        self.temperature_dyn_label.setObjectName("temperature_dyn_label")
        self.dyn_labels_layout.addWidget(self.temperature_dyn_label)
        self.horizontalLayout.addLayout(self.dyn_labels_layout)
        self.led_frame = QtWidgets.QFrame(self.tab)
        self.led_frame.setGeometry(QtCore.QRect(160, 710, 1421, 80))
        self.led_frame.setStyleSheet("background-color: rgb(140, 11, 66);")
        self.led_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.led_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.led_frame.setObjectName("led_frame")
        self.layoutWidget_2 = QtWidgets.QWidget(self.led_frame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 1411, 61))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_2 = temp_led(self.layoutWidget_2)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2.addWidget(self.widget_2)
        self.widget_3 = loads_online_led(self.layoutWidget_2)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_2.addWidget(self.widget_3)
        self.widget_4 = room_occupancy_led(self.layoutWidget_2)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_2.addWidget(self.widget_4)
        self.widget_5 = xtra_led(self.layoutWidget_2)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2.addWidget(self.widget_5)
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_3.setGeometry(QtCore.QRect(160, 0, 1421, 701))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.plotsLayout = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.plotsLayout.setContentsMargins(0, 0, 0, 0)
        self.plotsLayout.setObjectName("plotsLayout")
        self.voltage_plot = voltage_plot(self.layoutWidget_3)
        self.voltage_plot.setObjectName("voltage_plot")
        self.plotsLayout.addWidget(self.voltage_plot, 0, 0, 1, 1)
        self.current_plot = current_plot(self.layoutWidget_3)
        self.current_plot.setStyleSheet("background-color: rgb(140, 11, 66);")
        self.current_plot.setObjectName("current_plot")
        self.plotsLayout.addWidget(self.current_plot, 0, 1, 1, 1)
        self.widget = power_plot(self.layoutWidget_3)
        self.widget.setStyleSheet("background-color: rgb(140, 11, 66);")
        self.widget.setObjectName("widget")
        self.plotsLayout.addWidget(self.widget, 1, 0, 1, 1)
        self.temp_plot = temp_plot(self.layoutWidget_3)
        self.temp_plot.setObjectName("temp_plot")
        self.plotsLayout.addWidget(self.temp_plot, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(0, 0, 131, 141))
        self.label.setStyleSheet("border-image: url(:/img/NM_State_University_logo.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.line_9 = QtWidgets.QFrame(self.tab)
        self.line_9.setGeometry(QtCore.QRect(0, 140, 151, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(self.tab)
        self.line_10.setGeometry(QtCore.QRect(140, 0, 20, 841))
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(self.tab)
        self.line_11.setGeometry(QtCore.QRect(0, 390, 151, 20))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(-10, 400, 161, 131))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 141, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_numofloads_display = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_numofloads_display.setFont(font)
        self.label_numofloads_display.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_numofloads_display.setAlignment(QtCore.Qt.AlignCenter)
        self.label_numofloads_display.setObjectName("label_numofloads_display")
        self.verticalLayout.addWidget(self.label_numofloads_display)
        self.lineEdit_numofloads = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_numofloads.setFont(font)
        self.lineEdit_numofloads.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.lineEdit_numofloads.setMaxLength(3)
        self.lineEdit_numofloads.setCursorPosition(0)
        self.lineEdit_numofloads.setObjectName("lineEdit_numofloads")
        self.verticalLayout.addWidget(self.lineEdit_numofloads)
        self.pushButton_numofloads = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_numofloads.setFont(font)
        self.pushButton_numofloads.setObjectName("pushButton_numofloads")
        self.verticalLayout.addWidget(self.pushButton_numofloads)
        self.tab_1.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tab_1.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1719, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_1.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.voltage_label.setText(_translate("MainWindow", "Voltage:"))
        self.current_label.setText(_translate("MainWindow", "Current:"))
        self.power_label.setText(_translate("MainWindow", "Power:"))
        self.reactive_power_label.setText(_translate("MainWindow", "R Power:"))
        self.temperature_label.setText(_translate("MainWindow", "Temp:"))
        self.voltage_dyn_label.setText(_translate("MainWindow", "volta"))
        self.current_dyn_label.setText(_translate("MainWindow", "curre"))
        self.power_dyn_label.setText(_translate("MainWindow", "powerr"))
        self.reactive_power_dyn_label.setText(_translate("MainWindow", "rpower"))
        self.temperature_dyn_label.setText(_translate("MainWindow", "temp"))
        self.label_numofloads_display.setToolTip(_translate("MainWindow", "Number of loads currently on."))
        self.label_numofloads_display.setText(_translate("MainWindow", "0"))
        self.lineEdit_numofloads.setToolTip(_translate("MainWindow", "Enter a number of loads here."))
        self.pushButton_numofloads.setToolTip(_translate("MainWindow", "Enter number of loads to turn on."))
        self.pushButton_numofloads.setText(_translate("MainWindow", "Enter"))
        self.tab_1.setTabText(self.tab_1.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tab_1.setTabText(self.tab_1.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

from inLedWidgetV6 import *
from Outlet_1_DataPlotsV6 import *
import resources_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_InOutlet_1_Window()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())